version: '3.8'

services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped

  # Service de développement avec hot reload
  landing-page-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
